# Generated by Django 4.2.7 on 2026-02-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_expires_at_room_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
