# Generated by Django 4.2.7 on 2026-02-01 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, help_text='Profile picture (optional)', null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, help_text='Tell others about yourself', max_length=500)),
                ('timezone', models.CharField(default='UTC', help_text='Your timezone for scheduling', max_length=50)),
                ('total_study_minutes', models.IntegerField(default=0, help_text='Total minutes studied across all sessions')),
                ('study_streak', models.IntegerField(default=0, help_text='Consecutive days with study sessions')),
                ('longest_streak', models.IntegerField(default=0, help_text='Best streak ever achieved')),
                ('last_study_date', models.DateField(blank=True, help_text='Last date user studied', null=True)),
                ('total_xp', models.IntegerField(default=0, help_text='Experience points earned')),
                ('level', models.IntegerField(default=1, help_text='User level (starts at 1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite_rooms', models.ManyToManyField(blank=True, help_text='Rooms this user has favorited', related_name='favorited_by', to='rooms.room')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light Theme'), ('dark', 'Dark Theme')], default='dark', help_text='Light or dark theme', max_length=10)),
                ('background', models.CharField(default='library', help_text='Study room background', max_length=50)),
                ('ambient_sound', models.CharField(default='none', help_text='Background ambient sound', max_length=50)),
                ('sound_volume', models.IntegerField(default=50, help_text='Volume level 0-100')),
                ('auto_resume_sound', models.BooleanField(default=False, help_text='Auto-play sound when session starts')),
                ('default_focus_duration', models.IntegerField(default=25, help_text='Default focus session minutes')),
                ('default_break_duration', models.IntegerField(default=5, help_text='Default break minutes')),
                ('auto_start_breaks', models.BooleanField(default=False, help_text='Automatically start break after focus')),
                ('auto_start_focus', models.BooleanField(default=False, help_text='Automatically start focus after break')),
                ('sound_notification', models.BooleanField(default=True, help_text='Play sound when timer ends')),
                ('browser_notification', models.BooleanField(default=False, help_text='Show browser notification')),
                ('show_goals_panel', models.BooleanField(default=True, help_text='Show goals/tasks panel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
