# Generated by Django 4.2.7 on 2026-02-01 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Achievement name', max_length=100)),
                ('description', models.TextField(help_text='How to unlock this')),
                ('icon', models.CharField(default='🏆', help_text='Emoji icon', max_length=50)),
                ('criteria_type', models.CharField(choices=[('first_session', 'First Session'), ('total_minutes', 'Total Minutes'), ('streak_days', 'Streak Days'), ('total_sessions', 'Total Sessions'), ('level_reached', 'Level Reached'), ('deep_focus', 'Deep Focus Session')], max_length=50)),
                ('criteria_value', models.IntegerField(help_text='Required value to unlock')),
                ('xp_reward', models.IntegerField(default=50, help_text='XP bonus for unlocking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['criteria_value'],
            },
        ),
        migrations.AddField(
            model_name='studysession',
            name='completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='planned_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='session_type',
            field=models.CharField(choices=[('focus', 'Focus Session'), ('break', 'Break')], default='focus', max_length=10),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='What do you want to accomplish?', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Optional details or notes')),
                ('priority', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority')], default='medium', max_length=10)),
                ('due_date', models.DateField(blank=True, help_text='Optional deadline', null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='studysession',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='tracker.task'),
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
